/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_faircode_netguard_Util */

#ifndef _Included_eu_faircode_netguard_Util
#define _Included_eu_faircode_netguard_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_faircode_netguard_Util
 * Method:    jni_getprop
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_faircode_netguard_Util_jni_1getprop
  (JNIEnv *, jclass, jstring);

/*
 * Class:     eu_faircode_netguard_Util
 * Method:    is_numeric_address
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_faircode_netguard_Util_is_1numeric_1address
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
