/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_faircode_netguard_ServiceSinkhole */

#ifndef _Included_eu_faircode_netguard_ServiceSinkhole
#define _Included_eu_faircode_netguard_ServiceSinkhole
#ifdef __cplusplus
extern "C" {
#endif
#undef eu_faircode_netguard_ServiceSinkhole_SYSTEM_UID
#define eu_faircode_netguard_ServiceSinkhole_SYSTEM_UID 2000L
/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_start
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1start
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_run
 * Signature: (JIZI)V
 */
JNIEXPORT void JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1run
  (JNIEnv *, jobject, jlong, jint, jboolean, jint);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_get_mtu
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1get_1mtu
  (JNIEnv *, jobject);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_get_stats
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1get_1stats
  (JNIEnv *, jobject, jlong);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_pcap
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1pcap
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_socks5
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1socks5
  (JNIEnv *, jobject, jstring, jint, jstring, jstring);

/*
 * Class:     eu_faircode_netguard_ServiceSinkhole
 * Method:    jni_done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_faircode_netguard_ServiceSinkhole_jni_1done
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
